// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dypqcuszvhsyoulpxotb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cHFjdXN6dmhzeW91bHB4b3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzc3NTYsImV4cCI6MjA3MzAxMzc1Nn0.pP5QdWtibMVWdZdE5LHwKei3Bf2imtJabtau7Qgibio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});